begin
	DBMS_LOGMNR.START_LOGMNR(
		STARTSCN => ?,
		OPTIONS => 
			DBMS_LOGMNR.SKIP_CORRUPTION
			+DBMS_LOGMNR.NO_SQL_DELIMITER
			+DBMS_LOGMNR.NO_ROWID_IN_STMT
			+DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG
			+DBMS_LOGMNR.CONTINUOUS_MINE
			+DBMS_LOGMNR.COMMITTED_DATA_ONLY
			+DBMS_LOGMNR.STRING_LITERALS_IN_STMT
	);
end;